services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - micro.converter  
    restart: always

  rabbit:
    image: rabbitmq:4-management-alpine
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
      - 5552:5552
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - micro.converter  
    restart: always

  document_processor:
    container_name: document_processor
    build:
        context: ./document_processor
        dockerfile: dockerfile
    environment:
      - UPLOAD_DATA_VOLUME=/data/uploads
      - AMQP=amqp://guest:guest@rabbit:5672
    volumes:
      - ./uploads:/data/uploads  

    networks:
      - micro.converter

    depends_on:
      - db
      - rabbit  

  upload_service:
    container_name: upload_service
    build: 
      context: ./upload_service
      dockerfile: dockerfile
    env_file:
      - ./upload_service/app.env
    
    depends_on:
      - db
      - rabbit  
    
    environment:
      - UPLOAD_DATA_VOLUME=/data/uploads
      - AMQP=amqp://guest:guest@rabbit:5672
      - DB_SOURCE=postgres://postgres:mysecretpassword@db:5432/upload_service_dev?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/data/uploads  
    networks:
      - micro.converter

networks:
  micro.converter:
    driver: bridge  

volumes:
  postgres-data: 
  rabbitmq-data: 